% Author: Paolo Belardinelli

% Load T1w Nifti and define coord system. Doing this correctly is important for the rest
% Here, it is important to specify that our coordinate system is RAS
mripath     = './data_freesurfer_and_mri/EEGTMSseg_001or';
subjectname = 'EEGTMSseg_001';
mri         = ft_read_mri(fullfile(mripath,sprintf('%s.nii',subjectname)));
%%% check
mri = ft_determine_coordsys(mri, 'interactive', 'yes');
%% Volume realignment: LPA, RPA (see definition of those points) and Nasion need to be interactively defined
% For the moment, I have commented the coordinate system specification 
% since none of the supported formats complies with NeurOne (RAS, mm)
cfg          = [];
cfg.method   = 'interactive';
cfg.coordsys = 'ctf';
mri          = ft_volumerealign(cfg, mri);
%% Reslicing the voxels to make them cubic
cfg            = [];
cfg.resolution = 1;
cfg.dim        = [256 256 256];
mri            = ft_volumereslice(cfg, mri);
%% Tranformation matrix from mri to sensor space
transform_vox2ctf = mri.transform;
save(fullfile(mripath,sprintf('%s_transform_vox2ctf',subjectname)), 'transform_vox2ctf');
%% Writing MR volume in mgz format and sensor coordinates 
cfg             = [];
cfg.filename    = fullfile(mripath,sprintf('%sctf.mgz',subjectname));
cfg.filetype    = 'mgz';
cfg.parameter   = 'anatomy';
ft_volumewrite(cfg, mri);
%% Definition of 'acpc' Space
cfg          = [];
cfg.method   = 'interactive';
cfg.coordsys = 'acpc';
mri          = ft_volumerealign(cfg, mri);
%% Transformation from MRI to acpc
transform_vox2acpc = mri.transform;
save(fullfile(mripath,sprintf('%s_transform_vox2acpc',subjectname)), 'transform_vox2acpc');
%%
cfg          = [];
cfg.filename = fullfile(mripath,sprintf('%s.mgz',subjectname));
cfg.filetype = 'mgz';
cfg.parameter = 'anatomy';
ft_volumewrite(cfg, mri);
%%%
% Part out of Matlab/ Bash command line 
% export FREESURFER_HOME=<path to FreeSurfer>
% source $FREESURFER_HOME/SetUpFreeSurfer.sh
% export SUBJECTNAME=EEGTMSseg_048
% export SUBJECTS_DIR=/home/bnplab/mrt
% mksubjdirs $SUBJECTS_DIR/$SUBJECTNAME
% cd $SUBJECTS_DIR/$SUBJECTNAME/mri
% mri_convert -c -oc 0 0 0 $SUBJECTNAME.mgz orig.mgz  (this command is the most obscure: it takes an mgz and generates another mgz often shifted upwards)
% freeview -v orig.mgz (therefore it is necessary to check that the head of the subject is still entirely within the image)
% cp orig.mgz orig/001.mgz
% fieldtrip/bin/ft_freesurferscript.sh (execution of the 3 steps of recon-all)
% module load hcp-workbench (loading workbench, not always necessary)
% /home/bnplab/ft_postfreesurferscript.sh /home/bnplab/mrt/ EEGTMSseg_029B/home/bnplab/templates (creation of a midthickness layer between white and grey and decimation of the fs mesh. Coregistration with two atlases, also)
%

%% creating one single mesh out of the two hemispheres generated by the previous procedure.
mripath = './data_freesurfer_and_mri/';
subjectname = 'EEGTMSseg_001';
datapath = fullfile(mripath,subjectname,'workbench');
filename = fullfile(datapath,[subjectname,'.L.aparc.a2009s.8k_fs_LR.label.gii']);
sourcemodel = ft_read_headshape({filename, strrep(filename, '.L.', '.R.')});
mripath = './data_freesurfer_and_mri/EEGTMSseg_001or';
load(fullfile(mripath,[subjectname,'_transform_vox2acpc']));
load(fullfile(mripath,[subjectname,'_transform_vox2ctf']));

transform_acpc2ctf = transform_vox2ctf/transform_vox2acpc;
%% generating and saving the source model in sensor coordinates
sourcemodel = ft_transform_geometry(transform_acpc2ctf, sourcemodel);
sourcemodel.inside = sourcemodel.atlasroi>0;
sourcemodel = rmfield(sourcemodel, 'atlasroi');
save(fullfile(mripath,sprintf('%s_sourcemodel_15684',subjectname)), 'sourcemodel');
%% plotting the source model mesh

figure
ft_plot_mesh(sourcemodel, 'maskstyle', 'opacity', 'facecolor', 'black', 'facealpha', 0.25, 'edgecolor', 'red', 	'edgeopacity', 0.5);
